/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-v9YChMMdzBeZnh1q7EBxTPNofTIcZBWKsQaXtUlmdhBI-GWhqAPr1se3nuz3IgIaUMsIUbJEED7zRH5VrJCfMJGO5vjgZKADxoLGR3O-d2JwbJhCywsLweSJ",
  "tt": "tt-1-WtWx-2m-KOHiTatsmF5Cmvqnof3U8iPGZEbUQaaxtss=",
  "version": "2020-11-20"
}

export default ebconfig;