/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-JVCkpqqcVYKRcbbIMvLhjOquWrUfWlF-AA6zMA25Bbtufkc6skbZlVVR93XCyKz1kOzzUgyySTRJO4b8ZZqsAyraMchxv-DF9ed0ffsjdEb4GYJ2DXVz3rZ6",
  "tt": "tt-1-YgMmNclwdvy-1YizASlM3-WWR9iLiq-vlfxLLQNQhvs=",
  "version": "2020-11-20"
}

export default ebconfig;